name: Code Quality Scan

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: '21'

      - name: Cache Gradle Build Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('*/.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Set Execute Permissions for Gradle Wrapper
        run: chmod +x gradlew

      - name: Compile Project with Gradle
        run: ./gradlew build

      - name: Run Unit Tests with Jacoco
        run: ./gradlew test jacocoTestReport

      - name: Execute SonarCloud Analysis
        uses: sonarsource/sonarcloud-github-action@v3.0.0
        with:
          projectBaseDir: '.'
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
